services:
  - type: web
    name: job-recommendation-backend
    runtime: docker
    env: docker
    region: singapore
    plan: free
    numInstances: 1
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: ML_API_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: REDIS_HOST
        value: localhost
      - key: REDIS_PORT
        value: 6379
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: NOTIFICATION_QUEUE
        value: coinshift-notification-queue
