services:
  - type: web
    name: job-recommendation-backend
    runtime: docker
    env: docker
    region: singapore
    plan: free
    numInstances: 1
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ML_API_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: REDIS_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM_EMAIL
        sync: false
      - key: BREVO_FROM_NAME
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GRAFANA_OTLP_URL
        sync: false
      - key: GRAFANA_OTLP_AUTH
        sync: false
