package com.example.job_recommendation_backend.service.Impl;

import com.example.job_recommendation_backend.service.GoogleCalendarService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestTemplate;

import com.example.job_recommendation_backend.exception.CustomApiException;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.web.client.HttpClientErrorException;

@Service
public class GoogleCalanderServiceImpl implements GoogleCalendarService {

    @Value("${google.client.id}")
    private String clientId;

    @Value("${google.client.secret}")
    private String clientSecret;

    @Value("${google.refresh.token}")
    private String refreshToken;


    private final RestTemplate restTemplate;

    public GoogleCalanderServiceImpl(RestTemplate restTemplate) {
        this.restTemplate = restTemplate;
    }

    @Override
    public String createMeetLink(LocalDateTime startTime, String candidateEmail) {

        String accessToken = getAccessToken();

        String url = "https://www.googleapis.com/calendar/v3/calendars/primary/events?conferenceDataVersion=1";

        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(accessToken);
        headers.setContentType(MediaType.APPLICATION_JSON);

        // ✅ Using robust format: LocalDateTime + explicit timeZone name
        DateTimeFormatter formatter = DateTimeFormatter.ISO_LOCAL_DATE_TIME;
        String startIso = startTime.withNano(0).format(formatter);
        String endIso = startTime.withNano(0).plusHours(1).format(formatter);

        Map<String, Object> body = new HashMap<>();

        body.put("summary", "Technical Interview");
        body.put("description", "Interview with " + candidateEmail);

        // ✅ Explicitly providing timeZone prevents offset conflicts
        body.put("start", Map.of("dateTime", startIso, "timeZone", "Asia/Kolkata"));
        body.put("end", Map.of("dateTime", endIso, "timeZone", "Asia/Kolkata"));

        // ✅ Re-enabled attendees
        body.put("attendees", List.of(
                Map.of("email", candidateEmail)
        ));

        // ✅ Google Meet config
        body.put("conferenceData", Map.of(
                "createRequest", Map.of(
                        "requestId", UUID.randomUUID().toString(),
                        "conferenceSolutionKey", Map.of(
                                "type", "hangoutsMeet"
                        )
                )
        ));

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(body, headers);

        try {
            ResponseEntity<Map> response =
                    restTemplate.postForEntity(url, request, Map.class);

            if (response.getBody() == null) {
                throw new CustomApiException(HttpStatus.INTERNAL_SERVER_ERROR, "Empty response from Google API");
            }

            Map<String, Object> responseBody = response.getBody();

            // Extract conference data
            Object confObj = responseBody.get("conferenceData");

            if (!(confObj instanceof Map)) {
                throw new CustomApiException(HttpStatus.INTERNAL_SERVER_ERROR, "Invalid conference data");
            }

            Map<String, Object> conferenceData = (Map<String, Object>) confObj;

            Object entryObj = conferenceData.get("entryPoints");

            if (!(entryObj instanceof List)) {
                throw new CustomApiException(HttpStatus.INTERNAL_SERVER_ERROR, "Invalid entry points");
            }

            List<Map<String, Object>> entryPoints = (List<Map<String, Object>>) entryObj;

            if (entryPoints == null || entryPoints.isEmpty()) {
                throw new CustomApiException(HttpStatus.INTERNAL_SERVER_ERROR, "No meeting link generated by Google Meet");
            }

            return entryPoints.stream()
                    .filter(ep -> "video".equals(ep.get("entryPointType")))
                    .map(ep -> (String) ep.get("uri"))
                    .findFirst()
                    .orElse((String) entryPoints.get(0).get("uri"));

        } catch (HttpClientErrorException e) {
            throw new CustomApiException(HttpStatus.BAD_REQUEST, e.getResponseBodyAsString());
        } catch (Exception e) {
            throw new CustomApiException(HttpStatus.INTERNAL_SERVER_ERROR, "Google API error");
        }
    }

    private String getAccessToken() {

        String url = "https://oauth2.googleapis.com/token";

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);

        MultiValueMap<String, String> body = new LinkedMultiValueMap<>();
        body.add("client_id", clientId);
        body.add("client_secret", clientSecret);
        body.add("refresh_token", refreshToken);
        body.add("grant_type", "refresh_token");

        HttpEntity<MultiValueMap<String, String>> request =
                new HttpEntity<>(body, headers);

        try {
            ResponseEntity<Map> response =
                    restTemplate.postForEntity(url, request, Map.class);

            if (response.getBody() == null || response.getBody().get("access_token") == null) {
                throw new CustomApiException(HttpStatus.INTERNAL_SERVER_ERROR, "Failed to get access token");
            }

            return (String) response.getBody().get("access_token");

        } catch (Exception e) {
            throw new CustomApiException(HttpStatus.INTERNAL_SERVER_ERROR, "OAuth token generation failed");
        }
    }
}
